
export const FETCHING_USERS         = 'FETCHING_USERS';
export const FETCHING_USERS_SUCCESS = 'FETCHING_USERS_SUCCESS';
export const FETCHING_USERS_FAILURE = 'FETCHING_USERS_FAILURE';
export const SAVE_USERS             = 'SAVE_USERS';
export const SAVE_USER_SUCCESS      = 'SAVE_USER_SUCCESS';
export const SAVE_USER_FAILURE      = 'SAVE_USER_FAILURE';
export const SAVE_USER_RESET        = 'SAVE_USER_RESET';

export const FETCHING_SERVICE           = 'FETCHING_SERVICE';
export const FETCHING_SERVICE_SUCCESS   = 'FETCHING_SERVICE_SUCCESS';
export const FETCHING_SERVICE_FAILURE   = 'FETCHING_SERVICE_FAILURE';
export const SAVE_SERVICE               = 'SAVE_SERVICE';
export const SAVE_SERVICE_SUCCESS       = 'SAVE_SERVICE_SUCCESS';
export const SAVE_SERVICE_FAILURE       = 'SAVE_SERVICE_FAILURE';
export const SAVE_SERVICE_RESET         = 'SAVE_SERVICE_RESET';

export const FETCHING_POP           = 'FETCHING_POP';
export const FETCHING_POP_SUCCESS   = 'FETCHING_POP_SUCCESS';
export const FETCHING_POP_FAILURE   = 'FETCHING_POP_FAILURE';
export const SAVE_POP               = 'SAVE_POP';
export const SAVE_POP_SUCCESS       = 'SAVE_POP_SUCCESS';
export const SAVE_POP_FAILURE       = 'SAVE_POP_FAILURE';
export const SAVE_POP_RESET         = 'SAVE_POP_RESET';

export const FETCHING_SWITCHMODEL           = 'FETCHING_SWITCHMODEL';
export const FETCHING_SWITCHMODEL_SUCCESS   = 'FETCHING_SWITCHMODEL_SUCCESS';
export const FETCHING_SWITCHMODEL_FAILURE   = 'FETCHING_SWITCHMODEL_FAILURE';
export const GET_SWITCHMODEL                = 'GET_SWITCHMODEL';
export const GET_SWITCHMODEL_SUCCESS        = 'GET_SWITCHMODEL_SUCCESS';
export const GET_SWITCHMODEL_FAILURE        = 'GET_SWITCHMODEL_FAILURE';
export const SAVE_SWITCHMODEL               = 'SAVE_SWITCHMODEL';
export const SAVE_SWITCHMODEL_SUCCESS       = 'SAVE_SWITCHMODEL_SUCCESS';
export const SAVE_SWITCHMODEL_FAILURE       = 'SAVE_SWITCHMODEL_FAILURE';
export const SAVE_SWITCHMODEL_RESET         = 'SAVE_SWITCHMODEL_RESET';

export const FETCHING_SWITCHS           = 'FETCHING_SWITCHS';
export const FETCHING_SWITCHS_SUCCESS   = 'FETCHING_SWITCHS_SUCCESS';
export const FETCHING_SWITCHS_FAILURE   = 'FETCHING_SWITCHS_FAILURE';
export const GET_SWITCHS                = 'GET_SWITCHS';
export const GET_SWITCHS_SUCCESS        = 'GET_SWITCHS_SUCCESS';
export const GET_SWITCHS_FAILURE        = 'GET_SWITCHS_FAILURE';
export const SAVE_SWITCHS               = 'SAVE_SWITCHS';
export const SAVE_SWITCHS_SUCCESS       = 'SAVE_SWITCHS_SUCCESS';
export const SAVE_SWITCHS_FAILURE       = 'SAVE_SWITCHS_FAILURE';
export const SAVE_SWITCHS_RESET         = 'SAVE_SWITCHS_RESET';

export const LOGIN_USER = 'LOGIN_USER';
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const LOGIN_USER_FAILURE = 'LOGIN_USER_FAILURE';
