
export const FETCHING_USERS         = 'FETCHING_USERS';
export const FETCHING_USERS_SUCCESS = 'FETCHING_USERS_SUCCESS';
export const FETCHING_USERS_FAILURE = 'FETCHING_USERS_FAILURE';
export const SAVE_USERS             = 'SAVE_USERS';
export const SAVE_USER_SUCCESS      = 'SAVE_USER_SUCCESS';
export const SAVE_USER_FAILURE      = 'SAVE_USER_FAILURE';
export const SAVE_USER_RESET        = 'SAVE_USER_RESET';

export const FETCHING_SERVICE           = 'FETCHING_SERVICE';
export const FETCHING_SERVICE_SUCCESS   = 'FETCHING_SERVICE_SUCCESS';
export const FETCHING_SERVICE_FAILURE   = 'FETCHING_SERVICE_FAILURE';
export const SAVE_SERVICE               = 'SAVE_SERVICE';
export const SAVE_SERVICE_SUCCESS       = 'SAVE_SERVICE_SUCCESS';
export const SAVE_SERVICE_FAILURE       = 'SAVE_SERVICE_FAILURE';
export const SAVE_SERVICE_RESET         = 'SAVE_SERVICE_RESET';

export const LOGIN_USER = 'LOGIN_USER';
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const LOGIN_USER_FAILURE = 'LOGIN_USER_FAILURE';
